export type Block =
  | { type: 'heading'; text: string }
  | { type: 'subheading'; text: string }
  | { type: 'paragraph'; text: string }
  | { type: 'box'; variant: 'teal' | 'orange' | 'sky' | 'rose'; label: string; text: string }
  | { type: 'compare'; items: { label: string; title: string; detail: string }[] }
  | { type: 'flow'; steps: string[] }
  | { type: 'list'; items: string[] }
  | { type: 'checklist'; items: string[] }
  | { type: 'quote'; text: string }
  | { type: 'table'; headers: string[]; rows: string[][] }
  | { type: 'timeline'; items: { year: string; text: string }[] }
  | { type: 'callout'; text: string };

export type LessonModule = {
  id: number;
  title: string;
  subtitle: string;
  blocks: Block[];
};

export const lessons: LessonModule[] = [
  {
    id: 1,
    title: 'Redes e hierarquia urbana',
    subtitle: 'Como as cidades se conectam, influenciam e organizam o território.',
    blocks: [
      { type: 'heading', text: 'As cidades formam uma rede de relações' },
      { type: 'paragraph', text: 'Uma cidade não existe isolada. Ela troca pessoas, mercadorias, informações e decisões com outras cidades. Esse conjunto de conexões é a **rede urbana**, e sua organização revela diferentes níveis de influência.' },
      { type: 'box', variant: 'teal', label: 'Ideia central', text: 'Quanto mais diversificados e especializados são os serviços de uma cidade, maior tende a ser sua área de influência.' },
      { type: 'subheading', text: 'Rede urbana e relações entre cidades' },
      { type: 'paragraph', text: 'A **rede urbana** é o conjunto de fluxos que conecta cidades entre si. Esses fluxos incluem pessoas (deslocamentos pendulares, migrações), mercadorias, serviços, informações e decisões econômicas. A intensidade e a direção desses fluxos definem quais cidades comandam e quais são comandadas.' },
      { type: 'paragraph', text: 'Pense em uma cidade média do interior: seus moradores podem trabalhar localmente, mas para serviços especializados — uma faculdade específica, um hospital de referência, uma grande loja — precisam se deslocar para uma cidade maior. Essa dependência cria uma hierarquia.' },
      { type: 'subheading', text: 'Funções e áreas de influência' },
      { type: 'paragraph', text: 'Cada cidade exerce **funções urbanas** — atividades que ela oferece para sua população e para a população de outras cidades. Quanto mais rara e especializada a função, maior a **área de influência** da cidade. Uma capital estadual com universidades e grandes hospitais influencia dezenas de municípios vizinhos; uma vila com apenas comércio básico influencia apenas sua comunidade imediata.' },
      { type: 'box', variant: 'teal', label: 'Como cai na prova', text: 'As questões costumam descrever uma cidade e pedir que você identifique seu papel na rede urbana. Atenção: a área de influência não se mede apenas pela população, mas pela intensidade dos fluxos.' },
      { type: 'subheading', text: 'Hierarquia urbana' },
      { type: 'paragraph', text: 'A **hierarquia urbana** organiza as cidades segundo sua centralidade e seu alcance. Não é apenas uma questão de tamanho populacional: uma cidade menor pode ter grande centralidade se concentrar serviços raros. A hierarquia funciona em diferentes escalas — local, regional, nacional e global.' },
      { type: 'table', headers: ['Nível', 'Características', 'Exemplos'], rows: [
        ['Metrópole regional', 'Concentra serviços especializados e comanda uma ampla região', 'Campinas, Goiânia, Florianópolis'],
        ['Metrópole nacional', 'Sedes de empresas, grande infraestrutura, decisões nacionais', 'São Paulo, Rio de Janeiro'],
        ['Cidade global', 'Conecta a economia nacional ao sistema mundial', 'São Paulo'],
        ['Centro local', 'Atende o cotidiano imediato de pequenas comunidades', 'Vilas e cidades pequenas'],
      ]},
      { type: 'subheading', text: 'Metrópoles e regiões metropolitanas' },
      { type: 'paragraph', text: 'Uma **metrópole** é uma cidade que exerce forte centralidade sobre uma ampla área, concentrando funções de comando — sedes empresariais, universidades, hospitais especializados, centros financeiros. Quando uma metrópole cresce e integra municípios vizinhos em uma área funcionalmente conectada, forma-se uma **região metropolitana**.' },
      { type: 'paragraph', text: 'A região metropolitana não é uma única cidade, mas um conjunto de municípios que compartilham infraestrutura, transporte, serviços e deslocamentos cotidianos. O município central (a metrópole) comanda os fluxos, mas os municípios periféricos também participam da dinâmica — geralmente como áreas de moradia que abastecem a metrópole de trabalhadores.' },
      { type: 'subheading', text: 'Urbanização, metropolização e conurbação' },
      { type: 'paragraph', text: 'São três processos relacionados, mas distintos:' },
      { type: 'list', items: [
        '**Urbanização**: crescimento da população e das atividades urbanas em relação ao rural.',
        '**Metropolização**: concentração de funções de comando em uma cidade, que passa a articular uma região metropolitana.',
        '**Conurbação**: união física da mancha urbana de municípios vizinhos. As cidades se tocam, formando um tecido urbano contínuo — mas cada uma mantém sua própria administração.',
      ]},
      { type: 'box', variant: 'teal', label: 'Atenção', text: 'A conurbação é um fenômeno físico. A região metropolitana é uma organização funcional. Uma coisa pode existir sem a outra, embora frequentemente andem juntas.' },
      { type: 'subheading', text: 'Cidades globais' },
      { type: 'paragraph', text: 'As **cidades globais** (ou mundiais) são aquelas que conectam a economia nacional ao sistema financeiro e produtivo mundial. Concentram sedes de multinacionais, bolsas de valores, empresas de consultoria internacional e serviços altamente especializados. São nós estratégicos da economia globalizada.' },
      { type: 'paragraph', text: 'No Brasil, **São Paulo** é a principal cidade global. No mundo, exemplos incluem Nova York, Londres, Tóquio, Hong Kong e Singapura. O conceito foi desenvolvido pela geógrafa Saskia Sassen para descrever cidades que não são necessariamente as maiores, mas as mais conectadas ao fluxo global de capital.' },
      { type: 'subheading', text: 'Megacidades' },
      { type: 'paragraph', text: 'As **megacidades** são aglomerações urbanas com mais de **10 milhões de habitantes**. São fenômenos especialmente comuns em países em desenvolvimento — Tóquio, Délhi, Xangai, Mumbai, São Paulo e Cidade do México são exemplos.' },
      { type: 'paragraph', text: 'Atenção: uma megacidade não é necessariamente uma cidade global. Tóquio é ambas as coisas, mas Daca (Bangladesh) é uma megacidade sem o mesmo grau de comando econômico mundial. Tamanho e conexão global são dimensões diferentes.' },
      { type: 'subheading', text: 'Megalópoles' },
      { type: 'paragraph', text: 'Quando várias regiões metropolitanas se integram em um vasto corredor urbanizado, forma-se uma **megalópole**. É o estágio mais avançado de urbanização: um contínuo de cidades que compartilham infraestrutura, economia e fluxos em escala gigantesca.' },
      { type: 'paragraph', text: 'O exemplo clássico é o corredor **BosWash**, nos EUA, que liga Boston a Washington D.C. passando por Nova York e Filadélfia. No Japão, a megalópole de Tóquio-Yokohama-Nagoya-Osaka concentra mais de 50 milhões de pessoas. No Brasil, ainda não formamos uma megalópole clássica, mas o eixo Rio–São Paulo aponta nessa direção.' },
      { type: 'box', variant: 'teal', label: 'Resumo', text: 'Cidade → Metrópole → Megacidade (tamanho) → Megalópole (integração). Cidade global é uma categoria de conexão, não de tamanho.' },
      { type: 'callout', text: 'Questões de fixação: q01 a q06' },
    ],
  },
  {
    id: 2,
    title: 'Problemas sociais urbanos',
    subtitle: 'Segregação, direito à cidade e as disputas pelo espaço urbano.',
    blocks: [
      { type: 'heading', text: 'O espaço urbano é também espaço de disputa' },
      { type: 'paragraph', text: 'A cidade distribui oportunidades de forma desigual. O preço da terra, a localização dos empregos e a oferta de transporte produzem diferentes experiências para quem vive nela. Entender a **questão urbana** é entender quem se beneficia, quem é afetado e como o território muda.' },
      { type: 'subheading', text: 'Segregação socioespacial' },
      { type: 'paragraph', text: 'A **segregação socioespacial** é a separação física de grupos sociais com diferentes níveis de renda no espaço da cidade. Grupos de maior renda ocupam áreas bem servidas de infraestrutura, enquanto populações de menor renda são empurradas para periferias, encostas e áreas menos valorizadas — geralmente mais distantes dos empregos e piores em serviços.' },
      { type: 'paragraph', text: 'Isso não acontece por acaso. O **preço da terra urbana** funciona como um mecanismo de filtro: áreas centrais e bem localizadas se valorizam, tornando-se inacessíveis para quem ganha menos. A distância física se converte em desigualdade de tempo, acesso e oportunidades.' },
      { type: 'box', variant: 'orange', label: 'Olhar geográfico', text: 'Segregação não é apenas "morar longe". É ter acesso desigual a tempo, renda, serviços, segurança e participação nas decisões urbanas.' },
      { type: 'subheading', text: 'Exclusão socioespacial' },
      { type: 'paragraph', text: 'A **exclusão socioespacial** é um agravamento da segregação. Não é apenas a separação — é a privação de acesso a bens, serviços e oportunidades urbanas. Populações excluídas não apenas moram longe, mas também têm menos escolas, menos transporte, menos saúde e menos voz nas decisões da cidade.' },
      { type: 'paragraph', text: 'A exclusão se manifesta em favelas sem saneamento, loteamentos irregulares sem infraestrutura, população em situação de rua e ocupações de áreas de risco. O contraste entre bairros ricos e pobres dentro da mesma cidade é a expressão mais visível da desigualdade urbana.' },
      { type: 'subheading', text: 'Direito à cidade' },
      { type: 'paragraph', text: 'O **direito à cidade** é um conceito desenvolvido pelo geógrafo Henri Lefebvre. Não significa apenas ter uma casa — significa ter acesso democrático a tudo que a cidade oferece: serviços, mobilidade, cultura, participação política e condições de viver com dignidade.' },
      { type: 'paragraph', text: 'Na prática, o direito à cidade se traduz em políticas de habitação, transporte público de qualidade, participação popular no planejamento urbano e garantia de que o espaço público não seja capturado apenas por interesses privados. É um direito coletivo, não individual.' },
      { type: 'subheading', text: 'Função social da propriedade' },
      { type: 'paragraph', text: 'No Brasil, a Constituição e o **Estatuto da Cidade** (2001) estabelecem que a propriedade urbana deve cumprir uma **função social**. Isso significa que o direito de propriedade não é absoluto: o proprietário deve usar o imóvel de forma compatível com o interesse coletivo e o planejamento urbano.' },
      { type: 'paragraph', text: 'Instrumentos como o IPTU progressivo (que aumenta a taxa sobre imóveis ociosos) e a desapropriação com fins sociais existem justamente para garantir que a propriedade não seja usada apenas como reserva de valor especulativo enquanto faltam moradias na cidade.' },
      { type: 'subheading', text: 'Habitação e vulnerabilidade social' },
      { type: 'paragraph', text: 'A **habitação** é um dos eixos centrais da questão urbana. A falta de moradia digna atinge milhões de famílias e está diretamente ligada à vulnerabilidade social. Sem moradia adequada, é mais difícil acessar educação, saúde e trabalho formal.' },
      { type: 'paragraph', text: 'A vulnerabilidade se agrava quando a população ocupa áreas de risco — encostas íngremes, margens de rios, áreas sujeitas a alagamentos — porque é o que sobra do mercado formal de terra. A relação entre moradia e risco ambiental é uma das conexões mais cobradas em prova.' },
      { type: 'subheading', text: 'Gentrificação' },
      { type: 'paragraph', text: 'A **gentrificação** (do inglês *gentrification*) é a transformação de um bairro popular ou degradado em uma área valorizada, geralmente após investimentos em infraestrutura, segurança ou revitalização. Com a valorização, aluguéis e preços sobem e moradores antigos de menor renda são pressionados a sair.' },
      { type: 'flow', steps: ['investimento público ou privado', 'valorização imobiliária', 'elevação de aluguéis', 'saída de moradores antigos', 'mudança do perfil social do bairro'] },
      { type: 'box', variant: 'orange', label: 'Pergunta de prova', text: 'A gentrificação é sempre ruim? Não é simples assim: a revitalização pode trazer serviços e melhorias, mas sem políticas de proteção aos moradores originais, reproduz a exclusão sob nova forma.' },
      { type: 'subheading', text: 'Especulação imobiliária e valorização da terra urbana' },
      { type: 'paragraph', text: 'A **especulação imobiliária** ocorre quando terrenos ou imóveis são mantidos vazios ou subutilizados à espera de valorização. O especulador não constrói nem aluga — espera que a cidade cresça e o terreno se valorize para vender com lucro.' },
      { type: 'paragraph', text: 'Isso gera **vazios urbanos** em áreas bem localizadas, encarece a terra e empurra a população para periferias cada vez mais distantes. A cidade se expande de forma dispersa, aumentando o custo de infraestrutura e o tempo de deslocamento. A **valorização da terra urbana** é, assim, tanto consequência quanto motor da desigualdade.' },
      { type: 'subheading', text: 'Mobilidade urbana' },
      { type: 'paragraph', text: 'A **mobilidade urbana** é o conjunto de deslocamentos que as pessoas fazem na cidade — para trabalho, estudo, saúde e lazer. Uma cidade com boa mobilidade oferece opções rápidas, seguras e acessíveis. Uma cidade com mobilidade precária transforma o deslocamento em barreira social.' },
      { type: 'paragraph', text: 'No Brasil, a maioria das cidades priorizou o automóvel individual. O resultado: congestionamento, poluição e exclusão de quem não tem carro — geralmente a população de menor renda, que gasta mais tempo no transporte público precário.' },
      { type: 'subheading', text: 'Mobilidade urbana sustentável' },
      { type: 'paragraph', text: 'A **mobilidade urbana sustentável** prioriza modos coletivos e não motorizados: transporte público de qualidade, corredores de ônibus, metrô, ciclovias, calçadas amplas e seguras. O objetivo é reduzir emissões, desigualdade e tempo de deslocamento.' },
      { type: 'compare', items: [
        { label: 'MODELO TRADICIONAL', title: 'Prioriza o carro', detail: 'Mais asfalto, mais estacionamento, mais congestionamento, exclusão de quem não tem carro' },
        { label: 'MODELO SUSTENTÁVEL', title: 'Prioriza as pessoas', detail: 'Transporte coletivo, ciclovias, calçadas, menos emissões, mais equidade' },
      ]},
      { type: 'callout', text: 'Questões de fixação: q07 a q12' },
    ],
  },
  {
    id: 3,
    title: 'Problemas urbanos ambientais',
    subtitle: 'Os efeitos ambientais da urbanização e os caminhos para reduzi-los.',
    blocks: [
      { type: 'heading', text: 'Urbanizar transforma o ambiente' },
      { type: 'paragraph', text: 'As cidades alteram o ciclo da água, o clima local e a qualidade do ar. Essas mudanças não são inevitáveis: dependem de como o espaço é planejado, ocupado e cuidado. Entender a relação entre **urbanização e ambiente** é entender causas, consequências e possibilidades de intervenção.' },
      { type: 'subheading', text: 'Ilha de calor urbana' },
      { type: 'paragraph', text: 'A **ilha de calor urbana** é o aumento de temperatura nas áreas urbanas em comparação com áreas rurais vizinhas. A causa principal é a substituição da vegetação por materiais impermeáveis — concreto, asfalto, vidro — que absorvem calor durante o dia e o liberam à noite.' },
      { type: 'paragraph', text: 'Além dos materiais, contribuem a concentração de veículos, indústrias, aparelhos de ar-condicionado e a reduzida circulação de ar entre edifícios altos. O resultado: cidades mais quentes, maior consumo de energia (mais ar-condicionado) e desconforto térmico, sobretudo para quem não tem recursos para se proteger.' },
      { type: 'box', variant: 'sky', label: 'Causa e consequência', text: 'Mais asfalto + menos vegetação → mais absorção de calor → maior temperatura urbana → mais consumo de energia e desconforto.' },
      { type: 'subheading', text: 'Inversão térmica' },
      { type: 'paragraph', text: 'A **inversão térmica** é um fenômeno atmosférico que ocorre quando uma camada de ar mais quente fica acima de uma camada de ar mais frio, próximo ao solo. Normalmente, o ar quente sobe e dispersa poluentes. Na inversão, a camada quente funciona como uma "tampa" que impede a circulação vertical.' },
      { type: 'paragraph', text: 'O resultado é a **concentração de poluentes** próximos ao solo — fumaça, material particulado, gases de veículos e indústrias. Em cidades como São Paulo, a inversão térmica é comum no inverno, em dias secos e sem vento, e agrava problemas respiratórios. A inversão em si não produz poluição, mas impede que ela se disperse.' },
      { type: 'flow', steps: ['ar frio próximo ao solo', 'camada de ar quente acima (tampa)', 'poluentes não se dispersam', 'concentração de fumaça e gases', 'agravamento respiratório'] },
      { type: 'subheading', text: 'Enchentes, enxurradas e movimentos de massa' },
      { type: 'paragraph', text: 'A urbanização aumenta a ocorrência de **enchentes** (acúmulo de água em áreas planas), **enxurradas** (escoamento rápido e violento de água) e **movimentos de massa** (deslizamentos, quedas de barreiras, corridas de lama). As causas combinam fatores naturais e humanos.' },
      { type: 'list', items: [
        '**Impermeabilização do solo**: asfalto e concreto impedem a infiltração da água, que escoa rapidamente para rios e galerias.',
        '**Ocupação de fundos de vale e margens**: retira a vegetação que amorteceria o impacto das cheias.',
        '**Ocupação de encostas**: cortes no relevo e retirada de vegetação diminuem a estabilidade do terreno.',
        '**Drenagem inadequada**: galerias subdimensionadas não suportam chuvas intensas.',
      ]},
      { type: 'subheading', text: 'Ocupação de áreas de risco' },
      { type: 'paragraph', text: 'A **ocupação de áreas de risco** é consequência direta da segregação socioespacial. Populações de menor renda, sem acesso ao mercado formal de moradia, ocupam encostas íngremes, margens de rios e áreas sujeitas a alagamentos. Quando chove forte, essas áreas são as primeiras a sofrer.' },
      { type: 'box', variant: 'sky', label: 'Conexão importante', text: 'O risco ambiental urbano não é apenas natural — é social. Quem mora em área de risco não está lá por escolha, mas porque o mercado de terra expulsa a população de menor renda para os locais mais vulneráveis.' },
      { type: 'subheading', text: 'Saneamento básico' },
      { type: 'paragraph', text: 'O **saneamento básico** é um conjunto de serviços essenciais para a saúde e o ambiente urbanos. No Brasil, a Lei de Saneamento (2007) define quatro componentes:' },
      { type: 'list', items: [
        '**Abastecimento de água**: captação, tratamento e distribuição.',
        '**Esgotamento sanitário**: coleta e tratamento de esgoto.',
        '**Limpeza urbana e manejo de resíduos sólidos**: coleta, transporte e destinação de lixo.',
        '**Drenagem urbana**: escoamento de águas pluviais para evitar alagamentos.',
      ]},
      { type: 'paragraph', text: 'A falta de saneamento atinge sobretudo periferias e regiões pobres, gerando doenças de veiculação hídrica (diarreia, leptospirose, hepatite A) e contaminando rios e solo. É um problema ambiental e, ao mesmo tempo, social.' },
      { type: 'subheading', text: 'Resíduos sólidos, reciclagem e reaproveitamento' },
      { type: 'paragraph', text: 'Os **resíduos sólidos** são o que chamamos de lixo. A Política Nacional de Resíduos Sólidos (2010) estabelece uma hierarquia: **reduzir** (produzir menos), **reutilizar** (usar novamente), **reciclar** (transformar em novo material) e só então descartar o que sobra de forma adequada.' },
      { type: 'paragraph', text: 'A **reciclagem** transforma materiais — papel, plástico, metal, vidro — em novos produtos, reduzindo a extração de matérias-primas e o volume de lixo. Mas ela é mais eficiente quando acompanhada de **separação na origem** (em casa, no trabalho) e de coleta seletiva. Reciclar sem reduzir o consumo não resolve o problema.' },
      { type: 'subheading', text: 'Lixões e destinação adequada' },
      { type: 'paragraph', text: 'Os **lixões** são áreas de descarte a céu aberto, sem proteção ao solo, sem tratamento de chorume (líquido tóxico) e sem controle de gases. Contaminam solo, água e ar, e atraem catadores em condições precárias. A lei brasileira determina o fechamento dos lixões e sua substituição por **aterros sanitários** — que impermeabilizam o solo, captam chorume e gases, e controlam o impacto ambiental.' },
      { type: 'compare', items: [
        { label: 'LIXÃO', title: 'Descarte a céu aberto', detail: 'Sem proteção, contamina solo e água, expõe catadores, é proibido por lei' },
        { label: 'ATERRO SANITÁRIO', title: 'Descarte controlado', detail: 'Solo impermeabilizado, captação de chorume e gases, menor impacto' },
      ]},
      { type: 'subheading', text: 'Impactos do consumo e da produção' },
      { type: 'paragraph', text: 'O modelo de produção e consumo urbano gera grandes volumes de resíduos, emissões e consumo de recursos naturais. Cidades são simultaneamente as maiores produtoras de impactos ambientais e os espaços onde soluções podem ser implementadas — transporte coletivo, energia renovável, economia circular, áreas verdes e planejamento.' },
      { type: 'box', variant: 'sky', label: 'Síntese', text: 'Os problemas ambientais urbanos têm causas sociais. Reduzi-los exige planejamento, infraestrutura e políticas que ataquem ao mesmo tempo a desigualdade e a degradação ambiental.' },
      { type: 'callout', text: 'Questões de fixação: q13 a q18' },
    ],
  },
  {
    id: 4,
    title: 'Formação territorial e geopolítica africana',
    subtitle: 'Colonialismo, fronteiras, recursos e a diversidade do continente.',
    blocks: [
      { type: 'heading', text: 'A África é diversa e tem histórias conectadas' },
      { type: 'paragraph', text: 'A formação territorial africana foi profundamente marcada pelo colonialismo europeu, que dividiu territórios e reorganizou economias para atender interesses externos. Mas o continente não pode ser reduzido a conflitos ou carências: é um território diverso, com povos, religiões, economias e trajetórias históricas distintas.' },
      { type: 'subheading', text: 'Colonialismo e imperialismo' },
      { type: 'paragraph', text: 'O **colonialismo** é a ocupação e dominação de um território por uma potência estrangeira. O **imperialismo** é a fase em que as potências europeias, no século XIX, dividiram entre si quase todo o mundo — inclusive a África — em busca de matérias-primas, mercados consumidores e controle estratégico.' },
      { type: 'paragraph', text: 'A África foi o continente mais afetado. Antes da chegada dos europeus, existiam reinos, impérios e rotas comerciais milenares. A colonização reorganizou tudo: fronteiras, economias, línguas oficiais, religiões e hierarquias sociais. O impacto dessa reorganização ainda se reflete na geopolítica atual.' },
      { type: 'subheading', text: 'Partilha da África' },
      { type: 'paragraph', text: 'A **partilha da África** foi a divisão do continente entre potências europeias no final do século XIX, especialmente a partir da **Conferência de Berlim (1884-1885)**. Reino Unido, França, Alemanha, Bélgica, Portugal e Itália dividiram territórios entre si, traçando fronteiras com régua e compasso — sem consultar os povos que ali viviam.' },
      { type: 'timeline', items: [
        { year: 'Séc. XV–XVIII', text: 'Tráfico negreiro e primeiros entrepostos costeiros' },
        { year: '1884–85', text: 'Conferência de Berlim: partilha formal da África' },
        { year: 'Décadas de 1950–60', text: 'Onda de independências africanas' },
        { year: 'Séc. XXI', text: 'Conflitos herdados, disputas por recursos e integração regional' },
      ]},
      { type: 'box', variant: 'rose', label: 'Contexto histórico', text: 'As fronteiras coloniais frequentemente agruparam povos diferentes em um mesmo Estado e separaram um mesmo povo em dois ou mais países. Essa herança é fonte de conflitos até hoje.' },
      { type: 'subheading', text: 'Descolonização' },
      { type: 'paragraph', text: 'A **descolonização** é o processo de conquista da independência das colônias. Na África, ela se intensificou após a Segunda Guerra Mundial, nas décadas de 1950 e 1960. Muitos países conquistaram a independência política, mas herdaram fronteiras artificiais, economias dependentes e estruturas de poder desiguais.' },
      { type: 'paragraph', text: 'A descolonização não resolveu tudo. Em vários países, a independência foi seguida de guerras civis, golpes militares, regimes autoritários e conflitos étnico-políticos — em parte porque o Estado colonial não havia criado condições para uma transição estável.' },
      { type: 'subheading', text: 'África do Norte e África Subsaariana' },
      { type: 'paragraph', text: 'O continente africano é frequentemente dividido em duas grandes regiões:' },
      { type: 'compare', items: [
        { label: 'ÁFRICA DO NORTE', title: 'Mediterrânea e árabe-islâmica', detail: 'Egito, Líbia, Argélia, Marrocos, Tunísia. Predomínio de povos árabes, religião islâmica e clima desértico' },
        { label: 'ÁFRICA SUBSAARIANA', title: 'Tropical e diversa', detail: 'Ao sul do Saara. Centenas de grupos étnicos, religiões tradicionais, cristianismo e islamismo, climas variados' },
      ]},
      { type: 'paragraph', text: 'Atenção: a **África Subsaariana** não é um bloco homogêneo. Reúne países muito diferentes em renda, religião, idioma, história e estágio de desenvolvimento. Generalizações escondem diferenças importantes.' },
      { type: 'subheading', text: 'Conflitos territoriais, étnicos, religiosos e políticos' },
      { type: 'paragraph', text: 'Muitos conflitos africanos atuais têm raízes na herança colonial. As **fronteiras artificiais** agruparam povos diferentes ou separaram povos aparentados. Após a independência, disputas por poder, identidade e território se transformaram em guerras civis, secessões e genocídios.' },
      { type: 'paragraph', text: 'Os fatores são múltiplos e se combinam: disputas **étnicas** (entre grupos que foram forçados a partilhar um Estado), **religiosas** (entre comunidades islâmicas, cristãs e tradicionais), **políticas** (disputas por poder, golpes, regimes autoritários) e **econômicas** (controle de recursos). Explicar um conflito exige olhar para todos esses fatores — nunca para uma única causa.' },
      { type: 'subheading', text: 'Recursos naturais e interesses econômicos' },
      { type: 'paragraph', text: 'A África é rica em **recursos naturais**: petróleo, diamantes, ouro, cobre, coltan, terras agricultáveis. Mas essa riqueza muitas vezes alimenta conflitos em vez de desenvolvimento. O termo **"maldição dos recursos"** descreve situações em que a exploração de matérias-primas financia grupos armados, alimenta corrupção e mantém a população à margem.' },
      { type: 'paragraph', text: 'Interesses externos também estão presentes: empresas multinacionais e potências estrangeiras disputam acesso a minérios e petróleo. O controle de recursos é, assim, uma dimensão interna e externa da geopolítica africana.' },
      { type: 'subheading', text: 'Refugiados e deslocamentos populacionais' },
      { type: 'paragraph', text: 'Guerras, perseguições e catástrofes geram **deslocamentos forçados**. A África abriga milhões de **refugiados** (que cruzam fronteiras internacionais) e **deslocados internos** (que fogem dentro do próprio país). Esses deslocamentos pressionam serviços, reorganizam territórios e podem dar origem a novos Estados ou disputas.' },
      { type: 'paragraph', text: 'O fluxo de refugiados também é um tema geopolítico internacional: países vizinhos recebem grandes contingentes, e a migração para a Europa é objeto de acordos, barreiras e debates sobre direitos humanos.' },
      { type: 'subheading', text: 'Desigualdade socioeconômica' },
      { type: 'paragraph', text: 'A África concentra alguns dos países com piores índices de desenvolvimento humano (IDH), mas também tem nações em rápido crescimento econômico. A **desigualdade socioeconômica** é interna (entre elites e populações) e entre países. A herança colonial, a dependência econômica e os conflitos explicam grande parte desse quadro.' },
      { type: 'subheading', text: 'Dependência e produção de gêneros primários' },
      { type: 'paragraph', text: 'A economia de muitos países africanos ainda é estruturada na **exportação de produtos primários** — minérios, petróleo, café, cacau, algodão — e na **importação de manufaturados**. Essa inserção subordinada no comércio internacional torna os países vulneráveis às oscilações dos preços internacionais e dificulta a industrialização.' },
      { type: 'box', variant: 'rose', label: 'Conexão', text: 'A dependência econômica nasce da colonização, que reorganizou a África como fornecedora de matérias-primas. Superá-la exige industrialização, integração regional e diversificação produtiva.' },
      { type: 'subheading', text: 'Transição demográfica' },
      { type: 'paragraph', text: 'A **transição demográfica** é a passagem de um padrão de alta natalidade e alta mortalidade para baixa natalidade e baixa mortalidade. A África Subsaariana está em estágio inicial dessa transição: a mortalidade caiu (com avanços em saúde), mas a natalidade permanece alta. O resultado é **crescimento populacional acelerado**, com população jovem e pressão sobre serviços, emprego e infraestrutura.' },
      { type: 'paragraph', text: 'Esse crescimento pode ser oportunidade (força de trabalho, mercado consumidor) ou desafio (desemprego, migração, pressão social). Depende das políticas de educação, saúde e geração de emprego.' },
      { type: 'quote', text: 'Explicar um conflito exige olhar para a história, o território e os interesses envolvidos — nunca para uma única causa.' },
      { type: 'callout', text: 'Questões de fixação: q19 a q30' },
    ],
  },
];
